### ISSUE TITLE
CAPTCHA UPDATE WHEN

### ISSUE THREAD

**Issue by democratico** [IlIlIllIlIlIIlIlI/roblox-bruteforcer#1]
🙏🙏🙏🙏🙏

**Comment by IlIlIllIlIlIIlIlI** [comment]
i forgot this existed, working on it rn.
already done w/ api key changing from config so expect an update whenever i figure out how to load unpacked extensions 🙏

**Comment by IlIlIllIlIlIIlIlI** [comment]
posted updated w/ captcha support.

**Comment by democratico** [comment]
W MANZ

**Comment by IlIlIllIlIlIIlIlI** [comment]
its like mildly broken because of capsolver, ill check it out soon
